import type { Rule } from '../types/rule.js';

export const rules: Rule[] = [
  {
    name: 'exchange-high-priority',
    enabled: true,
    sources: ['binance', 'okx', 'bybit', 'coinbase', 'bitget'],
    threshold: 4,
    excludeKeywords: [
      '周报',
      '週報',
      '活动预告',
      '活動預告',
      '福利',
      '抽奖',
      '抽獎',
      '教程',
      '测验',
      '測驗',
      '交易赛',
      '交易賽',
      '交易競賽',
      '奖池',
      '獎池',
      '奖励',
      '獎勵',
      '空投活动',
      '空投活動',
      '迎新獎勵',
      '迎新奖励',
      '推荐好友',
      '邀請排行榜',
      '邀請',
      '拼圖',
      '直播',
      '學院',
      '嘉年華',
      '狂歡節',
      '最新活動',
      '理財',
      'Alpha',
      'Bybit Card',
      'TradFi',
      '機器人',
      '机器人',
      '借幣服務',
      '借币服务',
      '信用卡',
      '借记卡',
      '借記卡',
      'Credit/Debit Card',
      'Credit/Debit Cards',
      'Debit/Credit Card',
      'Debit/Credit Cards',
      'Buy Crypto',
      'Recurring Buy',
      'fiat-to-token listing',
      'fiat-to-token listings',
      'fiat balances',
      '快捷買幣',
      '赚币',
      '賺幣',
      '儲蓄',
      '手續費全免',
      '手续费全免',
      '返現',
      '返现'
    ],
    keywords: [
      { term: '上线', score: 4 },
      { term: '上線', score: 4 },
      { term: '即将上线', score: 4 },
      { term: '即將上線', score: 4 },
      { term: '现货上线', score: 4 },
      { term: '現貨上線', score: 4 },
      { term: '上币', score: 4 },
      { term: '上市', score: 4 },
      { term: '新币上线', score: 4 },
      { term: '新幣上線', score: 4 },
      { term: '合约上线', score: 4 },
      { term: '合約上線', score: 4 },
      { term: '永续合约', score: 2 },
      { term: '永續合約', score: 2 },
      { term: '下线', score: 4 },
      { term: '下線', score: 4 },
      { term: '下架', score: 4 },
      { term: '下市', score: 4 },
      { term: 'delist', score: 4 },
      { term: 'listing', score: 4 },
      { term: '暂停充提', score: 5 },
      { term: '暂停充值', score: 5 },
      { term: '暂停提现', score: 5 },
      { term: '暫停充提', score: 5 },
      { term: '暫停充值', score: 5 },
      { term: '暫停提現', score: 5 },
      { term: '恢复充提', score: 4 },
      { term: '恢复充值', score: 4 },
      { term: '恢复提现', score: 4 },
      { term: '恢復充提', score: 4 },
      { term: '恢復充值', score: 4 },
      { term: '恢復提現', score: 4 },
      { term: '充值服务', score: 2 },
      { term: '提现服务', score: 2 },
      { term: '维护', score: 3 },
      { term: '維護', score: 3 },
      { term: '维护和升级', score: 3 },
      { term: '維護和升級', score: 3 },
      { term: '维护公告', score: 3 },
      { term: '維護公告', score: 3 },
      { term: '网络升级', score: 4 },
      { term: '網絡升級', score: 4 },
      { term: '钱包升级', score: 4 },
      { term: '錢包升級', score: 4 },
      { term: '主网', score: 3 },
      { term: '主網', score: 3 },
      { term: '代币置换', score: 5 },
      { term: '代幣置換', score: 5 },
      { term: 'token swap', score: 5 },
      { term: 'swap', score: 4 },
      { term: '品牌升级', score: 4 },
      { term: '品牌升級', score: 4 },
      { term: '更名', score: 4 },
      { term: 'rebranding', score: 4 },
      { term: '资金费率', score: 3 },
      { term: '資金費率', score: 3 },
      { term: '风险限额', score: 3 },
      { term: '風險限額', score: 3 },
      { term: '保证金率', score: 3 },
      { term: '保證金率', score: 3 },
      { term: '保证金', score: 2 },
      { term: '保證金', score: 2 },
      { term: '杠杆', score: 2 },
      { term: '槓桿', score: 2 },
      { term: 'margin', score: 2 },
      { term: 'maintenance', score: 3 },
      { term: 'funding rate', score: 3 },
      { term: 'risk limit', score: 3 },
      { term: 'withdrawal suspended', score: 5 },
      { term: 'deposit suspended', score: 5 },
      { term: 'withdrawal resumed', score: 4 },
      { term: 'deposit resumed', score: 4 }
    ]
  },
  {
    name: 'panews-breaking',
    enabled: true,
    sources: ['panews'],
    threshold: 3,
    excludeKeywords: ['行情回顾', '专栏', '投稿', '研报精选'],
    keywords: [
      { term: 'SEC', score: 2 },
      { term: 'ETF', score: 2 },
      { term: '黑客', score: 3 },
      { term: '破产', score: 3 },
      { term: '被盗', score: 3 },
      { term: '融资', score: 2 },
      { term: '上线', score: 2 },
      { term: '下架', score: 2 },
      { term: '清算', score: 2 },
      { term: '黄金', score: 3 },
      { term: '孙宇晨', score: 3 },
      { term: '马斯克', score: 3 },
      { term: 'WLFI', score: 3 },
      { term: 'Polymarket', score: 3 },
      { term: 'MetaMask', score: 3 },
      { term: 'OpenAI', score: 3 },
      { term: '破产', score: 3 }
    ]
  },
  {
    // Threshold 4 with weighted tiers:
    //   5pt = single hit fires (chip-ban, IPO, GPT-N flagship)
    //   4pt = single hit fires (model release, major funding, AI Act, lawsuit)
    //   3pt = combo needed (medium catalysts: infra deal, pricing, partnership)
    //   2pt = noise filter (tech-blog vocabulary, only fires with another hit)
    // arXiv feeds intentionally excluded — paper titles match too many generic terms.
    name: 'ai-industry-catalyst',
    enabled: true,
    sources: [
      'openai_blog',
      'nvidia_blog',
      'google_ai_blog',
      'microsoft_ai_blog',
      'aws_ml_blog',
      'huggingface_blog',
      'gary_marcus',
      'ai_snake_oil',
      'pluralistic',
      'media_404'
    ],
    threshold: 4,
    excludeKeywords: [
      'newsletter',
      'weekly recap',
      'monthly digest',
      'tutorial',
      '教程',
      'we are hiring',
      "we're hiring",
      '招聘',
      'job opening',
      'AMA',
      'office hours'
    ],
    keywords: [
      // ---- 新模型发布 (model releases) ----
      { term: 'gpt-5', score: 5 },
      { term: 'gpt-6', score: 5 },
      { term: 'gpt5', score: 5 },
      { term: 'gpt6', score: 5 },
      { term: 'claude opus', score: 4 },
      { term: 'claude sonnet', score: 4 },
      { term: 'claude haiku', score: 4 },
      { term: 'gemini ultra', score: 4 },
      { term: 'gemini 3', score: 4 },
      { term: 'gemini 4', score: 4 },
      { term: 'llama 4', score: 4 },
      { term: 'llama 5', score: 4 },
      { term: 'deepseek-v', score: 4 },
      { term: 'deepseek v', score: 4 },
      { term: 'qwen', score: 3 },
      { term: 'frontier model', score: 4 },
      { term: 'foundation model', score: 3 },
      { term: 'new model', score: 3 },
      { term: 'introducing', score: 3 },
      { term: 'announcing', score: 3 },
      { term: 'now available', score: 3 },
      { term: 'general availability', score: 3 },
      { term: 'released', score: 2 },
      { term: '正式发布', score: 4 },
      { term: '正式上线', score: 4 },
      { term: '新一代', score: 3 },
      { term: '基座模型', score: 3 },
      { term: '通用大模型', score: 3 },

      // ---- 芯片禁令 / 出口管制 (chip bans / export controls) ----
      { term: 'export control', score: 5 },
      { term: 'export controls', score: 5 },
      { term: 'export ban', score: 5 },
      { term: 'entity list', score: 5 },
      { term: 'foreign direct product rule', score: 5 },
      { term: 'bureau of industry and security', score: 5 },
      { term: 'sanctioned', score: 4 },
      { term: 'sanctions', score: 3 },
      { term: '出口管制', score: 5 },
      { term: '实体清单', score: 5 },
      { term: '制裁', score: 4 },
      { term: '禁令', score: 4 },
      { term: 'h20', score: 3 },
      { term: 'h100', score: 2 },
      { term: 'h200', score: 2 },
      { term: 'b200', score: 2 },
      { term: 'b100', score: 2 },

      // ---- 重大融资 / IPO ----
      { term: 'raises $', score: 4 },
      { term: 'raised $', score: 4 },
      { term: 'series c', score: 4 },
      { term: 'series d', score: 4 },
      { term: 'series e', score: 4 },
      { term: 'series f', score: 4 },
      { term: 'tender offer', score: 4 },
      { term: 'ipo', score: 4 },
      { term: 's-1 filing', score: 5 },
      { term: 'goes public', score: 4 },
      { term: 'pre-ipo', score: 3 },
      { term: 'valuation', score: 3 },
      { term: 'billion valuation', score: 4 },
      { term: '融资', score: 4 },
      { term: '估值', score: 3 },
      { term: '招股书', score: 4 },
      { term: '上市', score: 3 },

      // ---- 基础设施合作 (infra partnerships) ----
      { term: 'data center', score: 3 },
      { term: 'datacenter', score: 3 },
      { term: 'gigawatt', score: 4 },
      { term: 'megawatt', score: 2 },
      { term: 'power purchase agreement', score: 5 },
      { term: ' ppa ', score: 4 },
      { term: 'supercomputer', score: 4 },
      { term: 'supercluster', score: 4 },
      { term: 'gpu cluster', score: 3 },
      { term: 'partners with', score: 4 },
      { term: 'partnership with', score: 4 },
      { term: ' partner ', score: 3 },
      { term: 'partner to', score: 3 },
      { term: 'multi-year deal', score: 3 },
      { term: 'acquires', score: 4 },
      { term: 'acquisition of', score: 4 },
      { term: 'unveils', score: 3 },
      { term: 'debuts', score: 3 },
      { term: 'launches', score: 3 },
      { term: 'launched', score: 2 },
      { term: 'announces', score: 2 },
      { term: 'announced', score: 2 },
      { term: 'announcement', score: 2 },
      { term: 'stargate', score: 4 },
      { term: 'nuclear power', score: 4 },
      { term: 'small modular reactor', score: 4 },
      { term: 'smr ', score: 2 },
      { term: '数据中心', score: 3 },
      { term: '智算中心', score: 4 },
      { term: '算力中心', score: 4 },
      { term: '东数西算', score: 4 },
      { term: '战略合作', score: 3 },

      // ---- 定价 / 限流调整 ----
      { term: 'rate limit', score: 3 },
      { term: 'rate-limit', score: 3 },
      { term: 'price drop', score: 4 },
      { term: 'price cut', score: 4 },
      { term: 'price reduction', score: 4 },
      { term: 'pricing update', score: 3 },
      { term: 'deprecate', score: 3 },
      { term: 'deprecation', score: 3 },
      { term: 'sunset', score: 3 },
      { term: 'discontinued', score: 3 },
      { term: '涨价', score: 4 },
      { term: '降价', score: 4 },
      { term: '调价', score: 3 },
      { term: '限流', score: 3 },
      { term: '配额', score: 2 },
      { term: '弃用', score: 3 },

      // ---- 监管草案 / 诉讼 / AI 事故 ----
      { term: 'ai act', score: 5 },
      { term: 'eu ai act', score: 5 },
      { term: 'executive order', score: 4 },
      { term: 'antitrust', score: 4 },
      { term: 'ftc investigation', score: 5 },
      { term: 'doj investigation', score: 5 },
      { term: 'subpoena', score: 4 },
      { term: 'lawsuit', score: 4 },
      { term: 'court ruling', score: 4 },
      { term: 'injunction', score: 4 },
      { term: 'consent decree', score: 4 },
      { term: 'copyright infringement', score: 4 },
      { term: 'class action', score: 4 },
      { term: 'data breach', score: 4 },
      { term: '监管草案', score: 5 },
      { term: '监管办法', score: 5 },
      { term: '征求意见稿', score: 4 },
      { term: '算法备案', score: 4 },
      { term: '生成式人工智能', score: 3 },
      { term: '网信办', score: 4 },
      { term: '工信部', score: 3 },
      { term: '反垄断', score: 4 },
      { term: '诉讼', score: 3 },

      // ---- 技术博客 (low-tier noise filter — only fires in combination) ----
      { term: 'open-source', score: 2 },
      { term: 'open source', score: 2 },
      { term: 'open weights', score: 3 },
      { term: 'state-of-the-art', score: 2 },
      { term: ' sota ', score: 2 },
      { term: 'context window', score: 2 },
      { term: 'long context', score: 2 },
      { term: 'multimodal', score: 2 },
      { term: 'agentic', score: 2 },
      { term: 'benchmark', score: 1 },
      { term: '开源', score: 2 },
      { term: '多模态', score: 2 },
      { term: '智能体', score: 2 },

      // ---- AI 公司 / 实验室名（低分，组合触发；单独出现不足以推送）----
      { term: 'openai', score: 2 },
      { term: 'anthropic', score: 2 },
      { term: 'deepmind', score: 2 },
      { term: 'deepseek', score: 3 },
      { term: 'mistral', score: 2 },
      { term: 'cohere', score: 2 },
      { term: 'xai', score: 2 },
      { term: 'perplexity', score: 2 },
      { term: 'nvidia', score: 2 },
      { term: 'google ai', score: 2 },
      { term: 'meta ai', score: 2 },
      { term: 'apple intelligence', score: 3 },
      { term: 'microsoft ai', score: 2 },
      { term: 'huggingface', score: 2 },
      { term: 'hugging face', score: 2 },

      // ---- AI 产品 / 模型名（低分，组合触发）----
      { term: 'gemini', score: 2 },
      { term: 'claude', score: 2 },
      { term: 'chatgpt', score: 2 },
      { term: 'copilot', score: 2 },
      { term: 'codex', score: 2 },
      { term: 'sora', score: 3 },
      { term: 'dall-e', score: 3 },
      { term: 'gpt-', score: 2 },
      { term: ' o3 ', score: 2 },
      { term: ' o4 ', score: 2 },
      { term: ' o5 ', score: 3 },
      { term: 'llama', score: 2 },
      { term: '通义千问', score: 2 },
      { term: 'kimi', score: 2 },
      { term: '豆包', score: 2 },

      // ---- 具体催化剂模式（针对历史数据回放中漏掉的真实标题）----
      { term: 'ai search', score: 4 },
      { term: ' ai mode ', score: 4 },        // 必须两端空格，否则会匹配 "AI model" 的子串
      { term: 'i/o 202', score: 3 },                 // I/O 2026 / 2027
      { term: 'content provenance', score: 4 },
      { term: 'first cpu', score: 4 },
      { term: 'first gpu', score: 4 },
      { term: 'new chip', score: 4 },
      { term: 'ai trial', score: 4 },
      { term: 'ai policy', score: 3 },
      { term: 'ai slop', score: 4 },
      { term: 'ai bubble', score: 4 },
      { term: 'ai backlash', score: 4 },
      { term: 'hyperscaling', score: 4 },
      { term: 'illusion of', score: 3 },
      { term: 'generative ai', score: 2 },
      { term: 'large language model', score: 2 },
      { term: 'death threats', score: 5 },
      { term: 'resigns', score: 3 },
      { term: 'whistleblower', score: 4 },
      { term: 'leaked', score: 3 },
      { term: 'leak', score: 2 },

      // ---- 监管补漏 ----
      { term: 'enforcement action', score: 4 },
      { term: 'cease and desist', score: 4 },
      { term: ' doj ', score: 2 },             // 两端空格，避免误中任意 d-o-j 子串
      { term: ' ftc ', score: 2 },
      { term: ' sec ', score: 2 }
    ]
  }
];
